### ISSUE TITLE
How to enable changes in ruuvi-names.properties correctly?

### ISSUE THREAD

**Issue by markulai** [Scrin/RuuviCollector#44]
Hi!

I edited ruuvi-names.properties with my MAC & new tags and placed it beside the .jar, but they don't seem to change the tag names in grafana from the MAC format? Service start/stop service does not seem to do the job either. Is there rebuild needed or how the configuration should work?

br,
Markus

**Comment by Scrin** [comment]
Rebuild should not be necessary, the ruuvi-names.properties should work identically with ruuvi-collector.properties in that sense; a collector restart is enough when the .properties file(s) are in the same directory as the jar being executed.

When names are set, they are stored in a separate tag within InfluxDB (in addition to the mac address) to not break existing dashboards or contraptions that relies on the mac. So to get "pretty names" rather than macs on the dashboards, you need to use the "name" tag rather than the "mac" tag in **WHERE**, **GROUP BY**, and/or **ALIAS BY**, for example:

![grafana tag](https://user-images.githubusercontent.com/6617316/71532281-4fdce380-28fb-11ea-9145-1eed7ee719d8.png)

Do note that in order to use the **$tag_** macros in **ALIAS BY**, the corresponding tag must be specified in a **GROUP BY** clause (there can be many, if you want to include both the name and the mac).

Does this work for you? If not, it would be helpful if you could provide a screenshot similar to the above of a panel config on your dashboard.
